# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dlr-scada-input
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

kafka:
  ip: ""

oag4csvDataVolume:
  accessMode: ReadWriteOnce
  size: 1G
  storageClass: standard

file-mover:
  folderMounts:
    input:
      enabled: true
      volume:
        emptyDir: {}
    output:
      enabled: true
      volume:
        persistentVolumeClaim:
          claimName: oag4csv-pvc
