# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

file-mover:
  folderMounts:
    input:
      enabled: true
      volume:
        emptyDir: {}
    output:
      enabled: true
      volume:
        persistentVolumeClaim:
          claimName: oag4csv-pvc

replicaCount: 1

image:
  repository: scada-parser
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

kafka:
  ip: ""
  topic: ""

ksql:
  host: kafka-cp-ksql-server:8088

oag4csvDataVolume:
  accessMode: ReadWriteOnce
  size: 1G
  storageClass: standard
