# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

file-mover:
  folderMounts:
    input:
      enabled: true
      volume:
        emptyDir: {}
    output:
      enabled: true
      volume:
        persistentVolumeClaim:
          claimName: scada-parser-pvc

replicaCount: 1

image:
  repository: ghcr.io/energinet-singularity/scada-parser/energinet-singularity/scada-parser
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.0.1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

kafka:
  ip: ""
  topic: ""

ksql:
  host: kafka-cp-ksql-server:8088
  stream: ""
  table: ""

scadaparserDataVolume:
  accessMode: ReadWriteOnce
  size: 1G
  storageClass: standard
