---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scada-parser-pvc
spec:
  accessModes:
    - {{ .Values.scadaparserDataVolume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.scadaparserDataVolume.size }}
  storageClassName: {{ .Values.scadaparserDataVolume.storageClass }}
