---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oag4csv-pvc
spec:
  accessModes:
    - {{ .Values.oag4csvDataVolume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.oag4csvDataVolume.size }}
  storageClassName: {{ .Values.oag4csvDataVolume.storageClass }}
